services:
  app:
    container_name: medusa_app_prs_shop
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:00@localhost:5432/prs_shop_db2
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: medusa_db_prs_shop
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 00
      POSTGRES_DB: prs_shop_db2
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prs_shop_db2"]
      interval: 2s
      timeout: 5s
      retries: 30

volumes:
  pg_data:
